# Website's icon url.
favicon: /images/favicon/favicon.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo: # /images/favicon/favicon.ico
  text: XoYo24

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-dark

# Navigation bar menu links.
menu:
  Archives: /archives
  Tags: /tags
  # Lifestyle: /categories/LifeStyle
  # Music: /categories/Music
  # Technology: /categories/Technology
  About: /about

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: true

# Share plugin settings.
share:
  type: sharethis
  install_url: https://platform-api.sharethis.com/js/sharethis.js#property=5d03dee04351e90012650a76&product=inline-share-buttons

# Comment plugin settings.
comment:
  type: disqus
  shortname: xoyo24

# Other plugins and their settings.
plugins:
  mathjax: true
  katex: false
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id: UA-66610976-1


# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  

# Links at the bottom of the page.
footer_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/xoyo24
  Twitter:
    icon: fab fa-twitter
    url: https://twitter.com/xoyo24
